version: '3.8'

services:
  ecommerce:
    image: ecommerce-image:latest
    ports:
      - "8080:8080"
    depends_on:
      - store
      - exchange
    networks:
      - ecommerce

  store:
    image: store-image:latest
    ports:
      - "8081:8080"
    networks:
      - ecommerce

  fidelity:
    image: fidelity-image:latest
    ports:
      - "8082:8080"
    networks:
      - ecommerce

  exchange:
    image: fault-tolerance-ecommerce-exchange:latest
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "8083:8080"
    networks:
      - ecommerce

networks:
  ecommerce:
    driver: overlay
